// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication3.Models;

public partial class EmployyeDetail
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Nationality { get; set; }

    public string CurrentResidence { get; set; }

    public string Idnumber { get; set; }

    public DateTime? DateOfbirth { get; set; }

    public string Title { get; set; }

    public string Remark { get; set; }

    public string Gender { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CretaedBy { get; set; }

    public virtual ICollection<EmployeeAddition> EmployeeAdditions { get; set; } = new List<EmployeeAddition>();
}