// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication3.Models;

public partial class EmployeeAddition
{
    public int Id { get; set; }

    public int EmpId { get; set; }

    public int TypeId { get; set; }

    public int QueId { get; set; }

    public virtual EmployyeDetail Emp { get; set; }

    public virtual Question Que { get; set; }

    public virtual TypeList Type { get; set; }
}