// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication3.Models;

public partial class Question
{
    public int Id { get; set; }

    public string Questions { get; set; }

    public byte Deleted { get; set; }

    public int? TypeId { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string UpadtedBy { get; set; }

    public DateTime? UpadtedDate { get; set; }

    public virtual ICollection<EmployeeAddition> EmployeeAdditions { get; set; } = new List<EmployeeAddition>();

    public virtual TypeList Type { get; set; }
}