// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication3.Models;

public partial class TypeList
{
    public int Id { get; set; }

    public string Type { get; set; }

    public byte Deleted { get; set; }

    public virtual ICollection<EmployeeAddition> EmployeeAdditions { get; set; } = new List<EmployeeAddition>();

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();
}